name: tea_post
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
     

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.8
  provider: ^6.0.1
  
  

  





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.2.4
flutter_native_splash:
  color: "#54a276"
  image: assets/images/splash_logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

  # color: "#ffffff"
  # image: assets/splash_full.png
  # color_dark: "#1a1a1a"
  # image_dark: assets/splash_full.png
  # android: true
  # ios: true
  # android_gravity: fill
  # ios_content_mode: scaleAspectFill 

  


flutter:

 
  uses-material-design: true

  assets:
    - assets/images/tea_post_logo.png
    - assets/images/add_icon.png
    - assets/images/splash_logo.png
 


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
